### ISSUE TITLE
Gzip Support Also Adds Support for Compression Bombs 💣

### ISSUE THREAD

**Issue by jhwgh1968** [jedireza/warc#13]
Currently, every time a record is read, it attempts to read the entire content body into memory. Now that gzip archives are supported, this is bad.

I have already created a valid WARC archive which is 12 MB on disk, but decompresses to over 10 GB. Sure enough, the `read_gzip` example tried to fill most of the memory on my machine before I killed it.

To avoid this, I would propose a new API, which returns _headers only_, and allows the user to either read or skip the body. That would allow them to avoid such large data streams, and skip to the next item in the archive.

I am working on this a little already, thinking about a future use case for this library. But before I get too far, I wanted to know how open the project is to this new API.

**Comment by jedireza** [comment]
Good call out. I like this idea.

**Comment by jhwgh1968** [comment]
Now that I have completed my first big split of the `Record` API, this is the next thing I will work on as I get time.

**Comment by jhwgh1968** [comment]
I have a basic start on this [on a WIP branch](https://github.com/jhwgh1968/warc/tree/split_warc_body).

Currently, I am splitting up all the data structures between headers and bodies. The goal is to allow separate handling for bodies as `Vec<u8>` (like they are now) or an opaque reader.

If I can solve that type puzzle, that should be enough to facilitate writing a read iterator with an [`nth()`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.nth) implementation which can skip over the bodies of large items and find the next one.

**Comment by jedireza** [comment]
Rad. That sounds great.

**Comment by jhwgh1968** [comment]
The API is starting to take shape now:

1. `Record<MissingBody>` doesn't have a body. The user can add one, which will turn it into one of the other types. Exporting it as-is results in a valid WARC record with a content length of zero and no payload,
1. `Record<BufferedBody>` describes the record you had before. The user can manipulate the body data at will, but _cannot use them with streams_ -- until they convert it to another type.
1. `Record<StreamingBody>` has a body that users cannot manipulate, but they can `read()` as many times as they like. All streaming bodies must implement `Clone` in order to pull this off in a generic way.

This allows for an API with great flexibility when reading WARC files:
1. A "full record" iterator returns `Record<BufferedBody>` items. If the user uses this, it's their responsibility to avoid compression bombs.
1. A "streaming record" iterator returns `Record<StreamingBody>` items. The user is thus able to detect large content lengths, or other record properties, and discard them.
1. A "raw record" iterator returns the `RawRecordHeaders` and no bodies, while keeping parallel access to the stream. This is mostly for handling invalid and semi-valid streams (which is my use case). Since these are not always valid, the user is responsible for picking the rest of the stream apart and resyncing themselves.

Bikeshedding is welcome, as it's starting to come together!

**Comment by jedireza** [comment]
This all sounds good. I have not had time to dig into the branch more yet. Mind creating a WIP PR so it's easier to comment on particular lines of code?

**Comment by jhwgh1968** [comment]
I will do that once I get time to work on this again. Hopefully soon. :crossed_fingers:

**Comment by jhwgh1968** [comment]
Opened #23

**Comment by jhwgh1968** [comment]
Closed by #23. The solution is very similar to the `read_filtered` example.
