### ISSUE TITLE
Proposal: Warc Headers should be Enum, not Strings

### ISSUE THREAD

**Issue by jhwgh1968** [jedireza/warc#16]
I am planning to do a lot of manipulation of WARC files, including manipulation and checking of headers. I think an enum makes that a lot more convenient, and more "Rust-like."

As an example, I am working on an API in #13 that lets users avoid large bodies. How would the user code look? With the current design based on strings, it would be something like this:

```
while let Some(header) = reader.next_header() {
    if header.get("content-length").unwrap() > 1024 * 1024 {
        continue;
    }
    // process reader.body()
}
```

With a enum, of course, it would be `get(WarcHeader::ContentLength)` or the like.

This may not seem like a big deal, but "stringly typed" APIs work against the usual patterns of Rust. Enums are encouraged by the language, because they provide a number of advantages:

1. Type checking: if you typed `get("Content-Legnth").unwrap()`, you wouldn't know until runtime you had made a typo, and then have to spot it. Enum values are known to the compiler, and its error message would have a "help suggestion" indicating it's a typo (thanks to special logic).
2. Fewer imports. Currently, the write examples import `warc::header::{CONTENT_LENGTH, WARC_DATE, WARC_IP_ADDRESS, WARC_RECORD_ID, WARC_TYPE}`. With a enum, it would be `warc::header::WarcHeader`.
3. Natural casting code, rather than a manual conversion anti-pattern. With a current unpublished branch I have, the casting between `enum` values and strings is written once, already works with `Display` and `Error`, and is attached to the type. The current method requires calling `to_lowercase` whenever a string is brought in. If I'm writing a new API, I have to remember to do that, or cause a significant bug.
4. Easier to use. We have both just been surprised at the behavior of string case, thinking it was a non-issue as required by the standard. By presenting an enum in the user interface, it can be _assuredly_ a non-issue, unless the user _opts into_ using a custom string header for some reason.
5. Future proof. I am already looking into storing alternate, non-string versions of headers like Content Length as integers. Having `get()` change its behavior based on the header you passed will be easier, because it allows an exhaustive enum, rather than a "maybe in the list" string match.

I think these benefits are worth the minor drawbacks:

1. API Incompatibility. This can be minimized with a `get_str()` on the header type, which accepts a string and does a cast. But it still would require an `0.3.0` version bump.
2. Slightly more RAM usage. Instead of one machine word containing a string pointer, my current enum will require two: one for the enum value, one for the string pointer if the value is `Unknown`. I don't think this is significant, as the number of headers is small in all but extremely rare cases.

What do you think?

**Comment by jedireza** [comment]
Yeah. I used to have much more elaborate code for headers: https://github.com/jedireza/warc/tree/8d69372fd2dc4b3c15dc3c45622675ae40511d5f/src/header

But I agree that it went a little too far. I agree with all the points you mentioned and thought about a lot of the same ergonomics you brought up.

I like this idea. :shipit:
