### ISSUE TITLE
serde support?

### ISSUE THREAD

**Issue by Uinelj** [jedireza/warc#24]
Hello,

I'm using the warc library and need to serialize WARC headers, a feature that is not yet supported/implemented.

Although one can say that serde support is not in the scope of the crate (which I believe is a valid point of view), I think that it would fit the potential usage of warc. 
Moreover,  serde could be a feature flag, thus letting the users decide!

I've already implemented a quick way of serializing headers in my [fork](https://github.com/Uinelj/warc/commit/e28fc3651ec7e0529e2d8437520fd7a91ce9c1e4), and would be glad to participate in implementing the feature in the main repository if needed :)

**Comment by jedireza** [comment]
Thanks @Uinelj. This diff seems pretty tame. I'm going to defer to @jhwgh1968

**Comment by jhwgh1968** [comment]
Hi @Uinelj, if you put back the `ToString` impl you deleted (which is used a lot), this is completely fine with me. Feel free to submit a PR.

That said, know that I am currently working on an API overhaul (slowly). I would not block you, but the next release (0.3.0) may be a while yet. You would have to base your work on current master until then.

**Comment by Uinelj** [comment]
If I'm not mistaken, the Rust docs states that `ToString` shouldn't be implemented directly, as implementing `Display` gets us the `ToString` implementation automagically. However if there's a reason to keep `ToString` only I'd be completely fine removing my change (and learning a bit more about Rust :))

I'll base my work on current as it is already the case.

**Comment by jhwgh1968** [comment]
> If I'm not mistaken, the Rust docs states that ToString shouldn't be implemented directly, as implementing Display gets us the ToString implementation automagically.

I missed that. LGTM then!

**Comment by jhwgh1968** [comment]
Closed by #25
