### ISSUE TITLE
Error Handling Improvements

### ISSUE THREAD

**Issue by jhwgh1968** [jedireza/warc#26]
Looking at my own library uses, there is one more thing I'd like to see before releasing a 0.3 version: better errors.

Right now, all parse errors and all I/O errors return the same information. This means doing smart error handling besides "just return it to the caller" is not easy, and printing out error information is not very useful. If there is an I/O error reading from the file, for instance, we have no way to give useful information about it back.

I would also make sure that we are following the [error handling guidelines for the future of Rust](https://blog.rust-lang.org/inside-rust/2021/07/01/What-the-error-handling-project-group-is-working-towards.html#guidelines-for-implementing-displayfmt-and-errorsource).

**Comment by jedireza** [comment]
Sounds great.

> I would also make sure that we are following the [error handling guidelines for the future of Rust](https://blog.rust-lang.org/inside-rust/2021/07/01/What-the-error-handling-project-group-is-working-towards.html#guidelines-for-implementing-displayfmt-and-errorsource).

Agreed.
