### ISSUE TITLE
It does not parse WARC file does it?

### ISSUE THREAD

**Issue by fulmicoton** [jedireza/warc#3]
The readme says it parses warc file...

**Comment by jedireza** [comment]
My work on parsing is on this branch https://github.com/jedireza/warc/tree/parsing

**Comment by fulmicoton** [comment]
That's great! I look forward to it.

But as you know, your readme is displayed crates.io, this is quite misleading.

**Comment by jedireza** [comment]
Not sure how it's misleading...

> The project is incomplete and the API is subject to change.

**Comment by fulmicoton** [comment]
I need a crate to parse WARC. I search WARC on crates.io and find your crate. 
Cool the README says it parse WARC.
Here is the important part : now I need to read the documentation and search through it for the non-existing API. That step would not be required if the README was correct. This is in that sense misleading.

Adding the mention `The project is incomplete ...` does not avoid this.

Ideally this should be in the README of the `parsing` branch, so that the commit is self documented, and README gets updated at the moment you merge the branch.

(Also, your README is 2 years old. Chances are your crate will never handle parsing.)
