### ISSUE TITLE
Reading gzip files is slow

### ISSUE THREAD

**Issue by fabricedesre** [jedireza/warc#30]
This is because the `GzipReader` is passed an unbuffered reader in `from_path_gzip()`

This is faster:

```rust
let file = std::fs::File::open(&self.path)?; // No need for write & create
let gzip_stream = GzipReader::new(BufReader::with_capacity(1 * MB, file))?;

let reader = WarcReader::new(BufReader::new(gzip_stream));
```

Testing with common crawl data, this takes a few seconds to read a ~300MB file instead of 2 minutes.

**Comment by jedireza** [comment]
Thanks for reporting @fabricedesre. If you have bandwidth for a PR it would be much appreciated.
