### ISSUE TITLE
Upload v0.3.0 to crates.io?

### ISSUE THREAD

**Issue by Uinelj** [jedireza/warc#35]
Hello,

The crate has been in `v0.3.0` for at least 8 months but the crates.io version is still `v0.2.1`, thus making the upload of crates depending on the latest developments of `warc` impossible.

Could it be possible to upload the version hosted on crates.io?

**Comment by jedireza** [comment]
Thanks for opening an issue. @jhwgh1968 do you think we're good to publish `0.3.0` as-is?

**Comment by jhwgh1968** [comment]
Between my own project work (what little I've done with this library in the past several months), and a lack of issues filed by others, I think we're good!

**Comment by jedireza** [comment]
Great. I'll publish as-is.

**Comment by jedireza** [comment]
`0.3.0` has been published: https://crates.io/crates/warc
