### ISSUE TITLE
default version should be "1.0", not "WARC/1.0"

### ISSUE THREAD

**Issue by catdevnull** [jedireza/warc#38]
https://github.com/jedireza/warc/blob/b2b9dfca0d81ed5a91e0016ea89022caf5283ec4/src/record.rs#L609

`WarcWriter` already writes `WARC/` in the headers, so setting the version to `WARC/1.0` prints `WARC/WARC/1.0` in the header. 

also, shouldn't version be an enum? :)

**Comment by jedireza** [comment]
Good catch and thank for reporting! I created https://github.com/jedireza/warc/pull/39 to fix.

> also, shouldn't version be an enum? :)

I don't think so because the version could be arbitrary. For example:

https://github.com/jedireza/warc/blob/b2b9dfca0d81ed5a91e0016ea89022caf5283ec4/src/parser.rs#L132-L135
